_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: es
uuid: 10ac318d-91ed-4e5e-8b73-5fa3c4ff2fda
name: 'Backend UCompensar'
mail: andresfelipealvarez@ucompensar.edu.co
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
